apiVersion: v1
kind: Namespace
metadata:
  name: example-cloud-armor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: example-cloud-armor
  name: example-cloud-armor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  namespace: example-cloud-armor
  name: example-cloud-armor
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http":"example-cloud-armor"}}'
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  namespace: example-cloud-armor
  name: example-cloud-armor
spec:
  securityPolicy:
    name: example-cloud-armor
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-cloud-armor
  namespace: example-cloud-armor
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "example-cloud-armor"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: example-cloud-armor
          servicePort: 80
